# Site settings
title: XM Front-End Development Framework and Guidelines
email: xm.richmedia@gmail.com
description: "XM Front-End Development frameworks and guidelines"
baseurl: ""
url: "http://xm-richmedia.github.io/"
twitter_username: jekyllrb
github_username:  xm-richmedia

# Build settings
markdown: kramdown
permalink: /guides/:title
