# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:    	  /guides/:title

# Setup
title:            XM Front-End Development Framework and Guidelines
tagline:          'XM Front-End Development Framework and Guidelines'
description:      'XM Front-End Development frameworks and guidelines'
url:              http://xm-richmedia.github.io
baseurl:          /

author:
name:             'xm-richmedia'
url:              http://xm-richmedia.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/XM-RichMedia
