# Dependencies
#markdown:         rdiscount
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter:      pygments
#pygments:         true
lsi:              false

# Permalinks
permalink:    	   /guides/:title

# Setup
title:            XM Front-End Development Guidelines and Documentation
tagline:          'XM Front-End Development Guidelines and Documentation'
description:      'XM Front-End Development Guidelines and Documentation'
url:              http://richmediateam.bitbucket.org/
baseurl:          /

author:
name:             'xm-richmedia'
url:              http://richmediateam.bitbucket.org/

paginate:         5

# Custom vars
version:          2.1.0

bitbucket:
  repo:           https://bitbucket.org/richmediateam

exclude: ['sass', 'node_modules', 'gulpfile.js', 'package.json', 'README.md', 'LICENSE.md']
