# Site settings
title: XM Front-End Developement Framework and Guidelines
email: xm.richmedia@gmail.com
description: "XM Front-End Development frameworks and guidelines"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  xm-richmedia

# Build settings
markdown: kramdown
permalink: pretty
